### ISSUE TITLE
Files not reloaded with PyCharm with Windows

### ISSUE THREAD

**Issue by nottheswimmer** [breuleux/jurigged#11]
## Description
On Windows, jurigged does not seem to reload a file it's running after I edit it with PyCharm. I have read this may be an issue with how WatchDog monitors for file updates, but I didn't see JetBrains IDEs mentioned specifically so I'm not sure if it's expected that this would work on them.

It may be nice to include a table of editors which are known to be compatible with jurigged, and any notes for making them work if necessary.

## Steps to reproduce

1. Create a new project in PyCharm
2. Write the script
```python
from time import sleep

def do_something():
    print("Hello")

def main():
    for _ in range(100):
        do_something()
        sleep(1)

if __name__ == '__main__':
    main()
```
3. Run the script with `jurigged -v main.py` in your terminal
4. As the script is printing "Hello" repeatedly, change `print("Hello")` to `print("Hi")` and click out of the file so it saves.

### Expected behavior

The script would go from printing "Hello" to "Hi"

### Actual behavior

The script continues to print "Hello"

### PyCharm version
PyCharm 2021.2.2 (Professional Edition)
Build #PY-212.5284.44, built on September 14, 2021

### Python version
Python 3.10.0

### Dependency versions
```
ansicon==1.89.0
blessed==1.19.0
codefind==0.1.2
jinxed==1.1.0
jurigged==0.3.4
ovld==0.3.2
six==1.16.0
watchdog==1.0.2
wcwidth==0.2.5
```

### Device specifications
```
Processor	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
```

### Windows specifications
```
Edition	Windows 11 Education Insider Preview
Version	Dev
Installed on	‎10/‎19/‎2021
OS build	22478.1012
Experience	Windows Feature Experience Pack 1000.22478.1012.0
```

**Comment by breuleux** [comment]
I am fairly sure this is the same issue as #9.

I have made adjustments to file watching in version 0.3.5, try installing that and tell me if that fixes the problem (I don't have Windows to test).
