### ISSUE TITLE
watchdog version is incompatible

### ISSUE THREAD

**Issue by yesdeepakmittal** [breuleux/jurigged#15]
When I install `jurigged`, by default it requires `watchdog` version *<2.0.0, >=1.0.2* and it automatically install `watch 1.0.2`. But `mkdocs 1.2.2` is also a dependency of `jurigged` which requires `watchdog >=2.0`. The `wathcdog 1.0.2` which install by default is incompatible with it. How to solve this dependency issue?

![image](https://user-images.githubusercontent.com/50262096/154405408-f700731b-f704-44b6-8a1d-16b84b4ee629.png)
![image](https://user-images.githubusercontent.com/50262096/154405444-7f65e76b-4aea-4ce5-a18d-0b6f7d3acf9f.png)

**Comment by breuleux** [comment]
Sorry, I forgot about this issue. Recent versions of watchdog seem to work fine with jurigged, so I relaxed the dependency requirement.
