### ISSUE TITLE
latest jurigged does not work with CPython 3.12.0

### ISSUE THREAD

**Issue by gjvc** [breuleux/jurigged#28]
I have used jurigged successfully and smoothly with Python 3.11 since the first release of the latter.  In the past week, I have tried upgrading to CPython 3.12.0 (on Linux) and while everything loads and runs as normal, hot-reloading doesn't happen.  Reverting the .venv/ to CPython 3.11 makes it work as before, as expected.

I am sorry for the lack of details and debugging; I mainly wanted to open this item as a sanity check for others. :-)

**Comment by breuleux** [comment]
It was an issue with module watching, I was defining this deprecated method without realizing: https://docs.python.org/3.11/library/importlib.html#importlib.abc.MetaPathFinder.find_module

I released v0.5.7 with a fix, thanks for putting this to my attention.

There may still be issues, there's at least one that makes the tests fail under 3.12 currently, but it's related to a different feature (editing code outside of the source files and pushing the changes to the source) so it's not as urgent.

**Comment by gjvc** [comment]
v0.5.7 is working just great for me now on 3.12
