### ISSUE TITLE
Idea for mapping between codes and functions

### ISSUE THREAD

**Issue by alexmojaki** [breuleux/jurigged#3]
Here's an idea for how you might be able to find the correct code and function objects. I'm not 100% sure if this would actually fit in the way you're doing things but I thought it might help. I also don't actually know how reliable `gc` is for this, it might be, but I haven't really investigated.

```python
import gc
import types


def find_subcodes(code):
    """
    Yields all code objects descended from this code object.
    e.g. given a module code object, will yield all codes defined in that module.
    """
    for const in code.co_consts:
        if isinstance(const, types.CodeType):
            yield const
            yield from find_subcodes(const)


def get_functions(code):
    """
    Returns functions that use the given code.
    """
    return [
        ref
        for ref in gc.get_referrers(code)
        if isinstance(ref, types.FunctionType)
           and ref.__code__ == code
    ]


module_code = compile("""
def foo():
    def bar():
        pass
    return bar
""", "<string>", "exec")

codes = list(find_subcodes(module_code))

exec(module_code)

bars = [foo(), foo()]

code_to_functions = {code: set(get_functions(code)) for code in codes}

print(code_to_functions)

assert code_to_functions == {foo.__code__: {foo}, bars[0].__code__: set(bars)}
```

**Comment by breuleux** [comment]
I thought about `gc.get_referrers` after I did most of the work, I figured it would help in some edge cases but not all that much.

I didn't think about getting the code objects from the module_code, though. That might actually be better than what I'm currently doing. I'm currently crawling the modules for functions and going through various pointers, but depending on what decorators are doing I can miss some, and I have to look through more objects than with your suggestion, with awkward stopping rules to limit the crawling. I don't like that part of the code very much. I'm not sure about the reliability of `gc` either, I think that at worst it might yield incomplete objects if it's trigged in the middle of them being constructed.

Still... I like this. I don't think it would be difficult to integrate. I think I'll test it out, I'll credit you if I end up going for it. Thanks a lot! :)

**Comment by breuleux** [comment]
Actually, I can't get the code object for an already imported module easily, can I?

**Comment by alexmojaki** [comment]
> Actually, I can't get the code object for an already imported module easily, can I?

No. I was hoping a similar gc trick could work but it looks like get_referrers doesn't let you go from co_consts up to the owning code, and also it looks like the module code is deleted after import.

Since you already have an import hook, you could extend it to do the actual module loading, including `compile` and `exec`. See https://github.com/alexmojaki/birdseye/blob/master/birdseye/import_hook.py for an example.

**Comment by breuleux** [comment]
I would still need a fallback for modules imported before jurigged, e.g. if someone uses the programmatic API to launch it in the middle of a debugging session. I'll keep it in mind, though.

Also, I think there's a simpler way to do it than import hooks or overriding the standard loader, which is to use `sys.addaudithook` (Python >= 3.8) to add an event listener on `exec`. As a bonus, it'd also trigger for code the user compiles and execs themselves.

**Comment by alexmojaki** [comment]
What about `gc.get_objects()`?

**Comment by breuleux** [comment]
Potentially expensive, and insofar that no reference is kept to these code objects, they're already gone and wouldn't show up in the list. Also for some reason I can't get _any_ code object to show up in `gc.get_objects()` and this is puzzling me.

**Comment by alexmojaki** [comment]
What I mean is what if you just looked through all functions in gc.get_objects()? Forget about my other suggestions.

**Comment by breuleux** [comment]
Ohh, okay 😅. That could work indeed, although I'd have to check how it performs when massive libraries have been imported.

**Comment by breuleux** [comment]
I implemented it, I had a few issues with tracking closures that this should fix. Thanks :)
