### ISSUE TITLE
`from __future__ import annotations` not respected

### ISSUE THREAD

**Issue by sweettuse** [breuleux/jurigged#36]
on recompile of a function definition change, jurigged does not respect `from __future__ import annotations`

say you have a module like this:

```python
from __future__ import annotations

def f(a: tuse) -> int:
    ...
```

and say you run `jurigged my_module.py`
and say you additionally change:
```python
def f(a: tuse) -> int:
# to
def f(a: tuse) -> str:
```
jurigged raises an error in reevaluation (`NameError: tuse is not defined` or something like that).

the reason is that the appropriate future flags aren't passed into the `compile` function.

i'll push a fix for this shortly, just wanted to create an issue first.

**Comment by acushner-rippling** [comment]
created #37 for this a few days ago, @breuleux if you want to take a look when you have a chance

**Comment by sweettuse** [comment]
created PR #37 for this issue a few days ago. @breuleux if you can take a look when you have a chance.

**Comment by benbuckman** [comment]
👋 Thanks for the fix here. Since the PR was merged, can this issue be closed? Thanks!

**Comment by breuleux** [comment]
Yeah, I had to publish a new version on PyPI first, so that's done.
