### ISSUE TITLE
No matching distribution found for jurigged

### ISSUE THREAD

**Issue by desprit** [breuleux/jurigged#6]
```
ERROR: Could not find a version that satisfies the requirement jurigged (from versions: none)
ERROR: No matching distribution found for jurigged
```

Pip 21.2.2
Python 3.7.11

Any idea on how to fix that, please?

**Comment by breuleux** [comment]
Unfortunately, Jurigged requires Python >= 3.8 (it uses the audithook system which was added in that version).

I added a line in the installation section of the README to specify this requirement.

A little tip: you can write `pip install jurigged -v` to get more detailed information about what went wrong. It's silly that you'd need to do that at all in this case, but that's pip's issue I suppose.

**Comment by desprit** [comment]
@breuleux 

Thank you for the tip about pip, that would certanly be helpful to see detailed info without explicitly providing a `v` flag. I'll switch the python3.8.
